services:
  web:
    build: .
    command: ${TODO_ARGUMENTS:-""}
    depends_on:
      - db
    environment:
      TODO_DB_HOST: db
    ports:
      - ${TODO_WEB_PORT:-8080}:${TODO_WEB_PORT:-8080}
  db:
    image: "postgres:16"
    environment:
      POSTGRES_DB: todo
      POSTGRES_PASSWORD: todopassword
      POSTGRES_USER: todouser
    ports:
      - "${TODO_DB_PORT:-5432}:5432"
