services:
  web:
    build: .
    command: ${TODO_ARGS:-""}
    depends_on:
      db:
        condition: service_healthy
    environment:
      TODO_DB_HOST: db
      TODO_DB_NAME: ${TODO_DB_NAME:-todo}
      TODO_DB_PORT: ${TODO_DB_PORT:-5432}
      TODO_DB_PW: ${TODO_DB_PW:-todopassword}
      TODO_DB_USER: ${TODO_DB_USER:-todouser}
      TODO_WEB_PORT: ${TODO_WEB_PORT:-8080}
    ports:
      - "${TODO_WEB_PORT:-8080}:${TODO_WEB_PORT:-8080}"
  db:
    image: "postgres:16"
    environment:
      PGPORT: ${TODO_DB_PORT:-5432}
      POSTGRES_DB: ${TODO_DB_NAME:-todo}
      POSTGRES_PASSWORD: ${TODO_DB_PW:-todopassword}
      POSTGRES_USER: ${TODO_DB_USER:-todouser}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h db -d ${TODO_DB_NAME:-todo} -U ${TODO_DB_USER:-todouser}",
        ]
      interval: 5s
      retries: 3
      timeout: 5s
    ports:
      - "${TODO_DB_PORT:-5432}:${TODO_DB_PORT:-5432}"
